language: python
python:
  - 2.7
install: pip install tox
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 2.7
    env: TOXENV=pylint
  allow_failures:
  - python: 2.7
    env: TOXENV=pylint
script:
  - tox -e $TOXENV
cache: pip
