language: python
python:
  - 2.7
install: pip install tox
env:
  global:
  - TOXENV=py27
  matrix:
  - TOXENV=lint
matrix:
  include:
    env: TOXENV=py27
  allow_failures:
    env: TOXENV=lint
script:
  - tox -e $TOXENV
cache: pip
