language: python
python:
  - 2.7
install: pip install tox
env:
  matrix:
    - TOXENV=py27
    - TOXENV=lint
matrix:
  include:
    - env: TOXENV=py27
    - env: TOXENV=lint
  allow_failures:
    env: TOXENV=lint
script:
  - tox -e $TOXENV
cache: pip
