language: python
python:
  - 2.7
install: pip install tox
env: TOXENV=py27
matrix:
  include:
    - env: TOXENV=py27
      python: 2.7
    - env: TOXENV=lint
      python: 2.7
  allow_failures:
    - env: TOXENV=lint
script:
  - tox -e $TOXENV
cache: pip
